### ISSUE TITLE
node-chaincode-utils dependency

### ISSUE THREAD

**Issue by daanporon** [wearetheledger/fabric-network-boilerplate#3]
Hi, thanks for sharing your code on how you are developing blockchain applications on Hyperledger Fabric. It’s great to see how other people are doing it. We saw that you are reusing some of the code we’ve written in our node-chaincode-utils (https://github.com/Kunstmaan/hyperledger-fabric-node-chaincode-utils) library and we where wondering why it was just copied in stead of depending on it? There is an npm package available for it as well: https://www.npmjs.com/package/@kunstmaan/hyperledger-fabric-node-chaincode-utils. We where wondering if there are any issues with it? Maybe not compatible with Typescript? If so we are open for feedback and contributions to improve this tool.

Kind regards,
Daan

**Comment by jestersimpps** [comment]
Hey Daan, nothing but respect for your library + code. We just wanted to start with a blank slate using typescript, hence we didn’t fork but decided to port some of the boilerplate from your library. Hope this doesn’t upset you. Best regards, Jo

**Comment by Superjo149** [comment]
Hi @daanporon ,
Like @jestersimpps said, it's a solid package, and we considered forking. But for our purpose, we fully seperated it.

The package you are talking about is now [here](https://github.com/wearetheledger/fabric-node-chaincode-utils), and also includes a mockstub for testing. We might seperate the mockstub in a seperate package for testing aswell.

**Comment by daanporon** [comment]
np, i was just wondering if there where any issues, because right now we have only been using it internally ... also with Typescript because we are also looking into that, so we would have appreciated a contribution making it Typescript compliant :) Now there are two libraries doing more or less the same ...

**Comment by Superjo149** [comment]
@daanporon mocking library seperated at https://github.com/wearetheledger/fabric-mock-stub
