### ISSUE TITLE
How do I create Car by sequence number ? 

### ISSUE THREAD

**Issue by YYSU** [wearetheledger/fabric-network-boilerplate#5]
Thanks for your contributing! Excuse me, I have a question.
In this example, how do I call the ```createCar()``` function by sequence number ?
```
createCar chaincode function - requires 5 args, ex: args: ['CAR12', 'Honda', 'Accord', 'Black', 'Tom'],
```
It should give the number manually now.

**Comment by jestersimpps** [comment]
We usually extend the objects we save with a 'docType' property. This property defines the category or type of the objects. You can then query fabric for all objects with this 'docType' and count them. When creating a new car, use this number to build your key.

In the method where you would call stubHelper.putState(), add the docType property to the car object and give it the value: 'CAR'

You could then use the getQueryResultAsList method to find all the objects of that docType:

`
   const cars = await stubHelper.getQueryResultAsList(
            {selector:{ docType: 'CAR'}}
   ); 
`
And store the car with the sequenced key:
`
const car = await stubHelper.putState('CAR'+cars.length , verifiedArgs.carsObject);
`
