### ISSUE TITLE
Default images does not exist for kafka & zookeeper

### ISSUE THREAD

**Issue by vanhumbeecka** [wearetheledger/fabric-network-boilerplate#9]
![image](https://user-images.githubusercontent.com/4650078/41397767-8602f14e-6fb5-11e8-9bce-b8e1f0aea1a9.png)

Using the ```preload.sh``` script gives this error on pulling the default (1.1.0) images

**Comment by Superjo149** [comment]
Try this script: https://github.com/hyperledger/fabric-samples/blob/master/scripts/bootstrap.sh
